---
title: "Explore Water Dataset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(cluster)
library(stringr)
```

#### 1.Read first line (which is head)
```{r}
water_data <- readRDS("data/processing/clean_water_data.Rds")
```

## Principal component analysis
```{r}
prcomp(water_data[ ,-(1:8)], scale = T) %>% summary()
```

```{r}
pca_result <- prcomp(water_data[ ,-(1:8)], scale = T)
pca_loadings <- pca_result$rotation
```
Transform matrix to tibble
```{r}
df_pca <- bind_cols(tibble(parameter = rownames(pca_loadings)),
                    as.tibble(pca_loadings)) %>% 
  gather(key = PC, value = PC_value, -parameter)
```

```{r}
df_pca %>% 
  group_by(PC) %>% 
  top_n(10, abs(PC_value)) %>% #abs(PC_value)
  #distinct(parameter, .keep_all = T) %>%
  View()
```
Подивимося на першу PC1 компоненту
```{r}
df_pca %>% 
  dplyr::filter(PC == 'PC1') %>% 
  mutate(parameter = substr(.$parameter, 1, 16)) %>% 
  ggplot(aes(x = reorder(parameter, PC_value), y = PC_value, fill = parameter)) +
  geom_col(show.legend = F) +
  labs(x = NULL) +
  coord_flip() 
  #reorder(parameter, PC_value)
```
Перевіримо, наскільки показники на різних "полюсах" графіка корелюють між собою
```{r}
water_data %>% 
  with(., cor.test(.$Sulfat_iony__mh_per_dm3, .$Syntetychni_poverxnevo_aktyvni_rechovyny__anionni___mh_per_dm3, method = 'pearson'))
#lm(Kysen_rozchynenyj_MhO2_per_dm3 ~ Amonij_iony__mh_per_dm3, data = water_data)
```
## k-means clusterization
Визначимо оптимальну кіл-ть кластерів
```{r}
#silhouette(k_means_res$cluster, dist((water_data[, -(1:8)])))
```

```{r}
k_means_res <- kmeans(water_data[, -(1:8)], centers = 6, nstart = 5)
```

```{r}
df_viz <- cbind(water_data, Cluster = k_means_res$cluster) 
```

