---
title: "Explore Water Dataset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(stringr)
```

#### 1.Read first line (which is head)
```{r}
water_data <- readRDS("data/processing/clean_water_data.Rds")
```

## water_data dataset
```{r}
water_data %>% 
  #dplyr::filter(Nazva_laboratoriyi == "Басейнова лабораторія моніторингу вод Сіверсько-Донецького БУВР") %>% 
  #count(Nazva_PS) %>% View()
  count(Nazva_laboratoriyi) %>% View()
```

```{r}
prcomp(water_data[ ,-(1:8)], scale = T) %>% summary()
```

```{r}
pca_result <- prcomp(water_data[ ,-(1:8)], scale = T, tol = .65)
#pca_result$rotation
```

```{r}
summary(pca_result)
```
## 
```{r}
df1 <- water_data %>% 
  mutate(year = year(water_data$Data_sposterezhen)) %>% 
  select(1:8, year, everything())
```
```{r}
df1 %>% 
  dplyr::filter(Rajon_richkovoho_basejnu == "Річки Причорномор'я") %>% 
  count(Nazva_laboratoriyi, Nazva_PS)
```
```{r}
df1 %>%
  dplyr::filter(Rajon_richkovoho_basejnu == "Річки Причорномор'я",
                year == 2014) %>% 
  group_by(year) %>% 
  summarise()
```

```{r}
ggplot(df1, aes(Dovhota, Shyrota)) +
  geom_point()
```




